// Code generated by "stringer -type=BillableStatus -linecomment"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Billable-1]
	_ = x[NonBillable-2]
	_ = x[NewBusiness-3]
}

const _BillableStatus_name = "UnknownBillableNon BillableNew Business"

var _BillableStatus_index = [...]uint8{0, 7, 15, 27, 39}

func (i BillableStatus) String() string {
	if i < 0 || i >= BillableStatus(len(_BillableStatus_index)-1) {
		return "BillableStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BillableStatus_name[_BillableStatus_index[i]:_BillableStatus_index[i+1]]
}
